services:
  spring:
    build:
      context: ./backend/todolist
      dockerfile: Dockerfile
    container_name: spring-todolist
    image: miguelcruzeiro/spring-todolist:v9
    volumes:
      - ./backend/todolist:/app
      - ./backend/todolist/.m2:/root/.m2
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    environment:
      COGNITO_JWKS_URL: ${COGNITO_JWKS_URL}
      EXTERNAL_AUTH_TOKEN_URL: ${EXTERNAL_AUTH_TOKEN_URL}
      EXTERNAL_AUTH_CLIENT_CREDENTIALS: ${EXTERNAL_AUTH_CLIENT_CREDENTIALS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: unless-stopped
    networks:
      - default

  angular:
    build: ./frontend
    container_name: angular-todolist
    stdin_open: true
    ports:
      - 4200:4200
    expose:
      - 4200
    restart: unless-stopped
    image: miguelcruzeiro/angular-todolist:v4
    networks:
      - default
    

networks:
  default:
    driver: bridge
